[
    {
       "id":0,
       "title":"Маргарита",
       "category":1,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":300,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/eb6d128bbcd340e98fd4f14b377e769f_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    },
    {
       "id":1,
       "title":"Чоризо фреш",
       "category":1,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":300,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":39
                },
                {
                   "size":45,
                   "addPrice":44
                },
                {
                   "size":50,
                   "addPrice":60
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/7a8164f7c43646e19c20001eaec9b031_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":33
                },
                {
                   "size":45,
                   "addPrice":45
                },
                {
                   "size":50,
                   "addPrice":50
                }
             ]
          }
       ]
    },
    {
       "id":2,
       "title":"Аррива",
       "category":0,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":200,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/8b6c71a280df4de59e24263df59c4cfa_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    },
    {
       "id":1,
       "title":"Маргарита",
       "category":0,
       "data":[
          {
             "name":"Цыпленок барбекю",
             "basePrice":400,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/57157f013c164840a24c1d49c7adb3b6_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":122
                },
                {
                   "size":45,
                   "addPrice":253
                },
                {
                   "size":50,
                   "addPrice":289
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    },
    {
       "id":1,
       "title":"Диабло",
       "category":1,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":340,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/2ac448e39ba24623a33c1d8d50b69ef8_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    },
    {
       "id":6,
       "title":"Колбаски барбекю",
       "category":1,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":377,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/20734006e66d427fb2cbb8fbb595b21e_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":123
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    },
    {
       "id":7,
       "title":"Чизбургер-пицца",
       "category":2,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":300,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/3bc057459afb4b2b8f2781bd1895b3a9_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    },
    {
       "id":8,
       "title":"Маргарита",
       "category":1,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":300,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/eb6d128bbcd340e98fd4f14b377e769f_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    },
    {
       "id": 9,
       "title":"Додо",
       "category":1,
       "data":[
          {
             "name":"Традиционное",
             "basePrice":344,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f773f5016e154a7f963377494e14d6d4_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          },
          {
             "name":"Тонкое",
             "basePrice":250,
             "imageUrl":"https://cdn.dodostatic.net/static/Img/Products/f440c85c436a4284afad6ecfc43c1fab_292x292.jpeg",
             "sizes":[
                {
                   "size":30,
                   "addPrice":100
                },
                {
                   "size":45,
                   "addPrice":230
                },
                {
                   "size":50,
                   "addPrice":300
                }
             ]
          }
       ]
    }
 ]